language: R
pandoc_version: 2.0.6
sudo: false

cache:
  packages: yes

addons:
  apt:
    packages:
      - libxml2-dev
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master