---
title: "Test"
author: "MAD"
date: "27 avril 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

N1 <- function(ech){
  return(round(2*median(ech)-1))
}

N2 <- function(ech){
  return(round(2*mean(ech)-1))
}

N3 <- function(ech){
  return(round(max(ech)+min(ech)-1))
}

N4 <- function(ech){
  return(round((length(ech)+1)/length(ech)*max(ech)-1))
}

N5 <- function(ech){
  return(round((max(ech)-min(ech))*(length(ech)+1)/(length(ech)-1)))
}
```

## Librairies

```{r}
library(tidyverse)
library(ggridges)
```

## Création échantillons

```{r}
N <- 500
n <- 50
iter <- 5000
pop <- c(1:N)

ech <- tibble(id = map(1:iter, ~sample(pop, n, replace = TRUE)))
ech <- ech %>%
  mutate(N1 = map_dbl(id, N1)) %>%
  mutate(N2 = map_dbl(id, N2)) %>%
  mutate(N3 = map_dbl(id, N3)) %>%
  mutate(N4 = map_dbl(id, N4)) %>%
  mutate(N5 = map_dbl(id, N5)) %>%
  gather(estimateur, valeur, N1, N2, N3, N4, N5)
```

## Graphiques

```{r}
ggplot(data = ech, mapping = aes(x = valeur, fill = estimateur))+
  geom_histogram(bins = 50)+
  facet_grid(estimateur~.)+
  geom_vline(xintercept=N,linetype=2,color="black")
```

